# clock 
set_property PACKAGE_PIN W5 [get_ports {CLK}]
	set_property IOSTANDARD LVCMOS33 [get_ports {CLK}]

#RST
set_property PACKAGE_PIN T18 [get_ports {RST}]
	set_property IOSTANDARD LVCMOS33 [get_ports {RST}]

	
# Switches 
set_property PACKAGE_PIN V17 [get_ports {DATO[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[0]}]
set_property PACKAGE_PIN V16 [get_ports {DATO[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[1]}]
set_property PACKAGE_PIN W16 [get_ports {DATO[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[2]}]
set_property PACKAGE_PIN W17 [get_ports {DATO[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[3]}]
set_property PACKAGE_PIN W15 [get_ports {DATO[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[4]}]
set_property PACKAGE_PIN V15 [get_ports {DATO[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[5]}]
set_property PACKAGE_PIN W14 [get_ports {DATO[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[6]}]
set_property PACKAGE_PIN W13 [get_ports {DATO[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[7]}]
set_property PACKAGE_PIN V2 [get_ports {DATO[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[8]}]
set_property PACKAGE_PIN T3 [get_ports {DATO[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[9]}]
set_property PACKAGE_PIN T2 [get_ports {DATO[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[10]}]
set_property PACKAGE_PIN R3 [get_ports {DATO[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[11]}]
set_property PACKAGE_PIN W2 [get_ports {DATO[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DATO[12]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED[8]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED[9]}]                    
     set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED[10]}]                    
     set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED[11]}]                    
     set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property PACKAGE_PIN P3 [get_ports {LED[12]}]                    
     set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]


##7 segment display
set_property PACKAGE_PIN W7 [get_ports {SEG_AG[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG_AG[0]}]
set_property PACKAGE_PIN W6 [get_ports {SEG_AG[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG_AG[1]}]
set_property PACKAGE_PIN U8 [get_ports {SEG_AG[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG_AG[2]}]
set_property PACKAGE_PIN V8 [get_ports {SEG_AG[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG_AG[3]}]
set_property PACKAGE_PIN U5 [get_ports {SEG_AG[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG_AG[4]}]
set_property PACKAGE_PIN V5 [get_ports {SEG_AG[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG_AG[5]}]
set_property PACKAGE_PIN U7 [get_ports {SEG_AG[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SEG_AG[6]}]

set_property PACKAGE_PIN U2 [get_ports {AND_30[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AND_30[0]}]
set_property PACKAGE_PIN U4 [get_ports {AND_30[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AND_30[1]}]
set_property PACKAGE_PIN V4 [get_ports {AND_30[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AND_30[2]}]
set_property PACKAGE_PIN W4 [get_ports {AND_30[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {AND_30[3]}]
set_property PACKAGE_PIN V7 [get_ports {DP}]					
        set_property IOSTANDARD LVCMOS33 [get_ports {DP}]	
	
        
      